"""add_product_catalog

Revision ID: 0f5706368502
Revises: 66351b967c70
Create Date: 2026-03-01 18:59:58.612155

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0f5706368502'
down_revision: Union[str, Sequence[str], None] = '66351b967c70'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('product_catalog',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('normalized_key', sa.String(length=300), nullable=False),
    sa.Column('canonical_name', sa.String(length=500), nullable=False),
    sa.Column('brand_id', sa.Integer(), nullable=True),
    sa.Column('gender', sa.String(length=20), nullable=True),
    sa.Column('subcategory', sa.String(length=100), nullable=True),
    sa.Column('tags', sa.Text(), nullable=True),
    sa.Column('trend_score', sa.Float(), nullable=True),
    sa.Column('listing_count', sa.Integer(), nullable=False),
    sa.Column('min_price_krw', sa.Integer(), nullable=True),
    sa.Column('max_price_krw', sa.Integer(), nullable=True),
    sa.Column('is_sale_anywhere', sa.Boolean(), nullable=True),
    sa.Column('first_seen_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['brand_id'], ['brands.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_product_catalog_brand_id'), 'product_catalog', ['brand_id'], unique=False)
    op.create_index(op.f('ix_product_catalog_gender'), 'product_catalog', ['gender'], unique=False)
    op.create_index(op.f('ix_product_catalog_normalized_key'), 'product_catalog', ['normalized_key'], unique=True)
    op.create_index(op.f('ix_product_catalog_subcategory'), 'product_catalog', ['subcategory'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_product_catalog_subcategory'), table_name='product_catalog')
    op.drop_index(op.f('ix_product_catalog_normalized_key'), table_name='product_catalog')
    op.drop_index(op.f('ix_product_catalog_gender'), table_name='product_catalog')
    op.drop_index(op.f('ix_product_catalog_brand_id'), table_name='product_catalog')
    op.drop_table('product_catalog')
    # ### end Alembic commands ###
