"""add_purchase_watchlist_drop

Revision ID: 25da360cc994
Revises: c3ad818a067f
Create Date: 2026-02-26 21:28:25.580194

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '25da360cc994'
down_revision: Union[str, Sequence[str], None] = 'c3ad818a067f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('purchases',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('product_key', sa.String(length=300), nullable=False),
    sa.Column('product_name', sa.String(length=500), nullable=False),
    sa.Column('brand_slug', sa.String(length=200), nullable=True),
    sa.Column('channel_name', sa.String(length=200), nullable=False),
    sa.Column('channel_url', sa.String(length=1000), nullable=True),
    sa.Column('paid_price_krw', sa.Integer(), nullable=False),
    sa.Column('original_price_krw', sa.Integer(), nullable=True),
    sa.Column('purchased_at', sa.DateTime(), nullable=False),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_purchases_product_key'), 'purchases', ['product_key'], unique=False)
    op.create_table('watchlist',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('watch_type', sa.String(length=50), nullable=False),
    sa.Column('watch_value', sa.String(length=300), nullable=False),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('watch_type', 'watch_value', name='uq_watchlist_item')
    )
    op.create_table('drops',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('brand_id', sa.Integer(), nullable=True),
    sa.Column('product_name', sa.String(length=500), nullable=False),
    sa.Column('product_key', sa.String(length=300), nullable=True),
    sa.Column('source_url', sa.String(length=1000), nullable=False),
    sa.Column('image_url', sa.String(length=1000), nullable=True),
    sa.Column('price_krw', sa.Integer(), nullable=True),
    sa.Column('release_date', sa.Date(), nullable=True),
    sa.Column('status', sa.String(length=50), nullable=False),
    sa.Column('detected_at', sa.DateTime(), nullable=False),
    sa.Column('notified_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['brand_id'], ['brands.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_drops_product_key'), 'drops', ['product_key'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_drops_product_key'), table_name='drops')
    op.drop_table('drops')
    op.drop_table('watchlist')
    op.drop_index(op.f('ix_purchases_product_key'), table_name='purchases')
    op.drop_table('purchases')
    # ### end Alembic commands ###
