"""add_tier_description_ko_to_brand_add_collab_news_tables

Revision ID: 66fc59a1f128
Revises: 
Create Date: 2026-02-26 00:39:04.433991

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '66fc59a1f128'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('fashion_news',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('entity_type', sa.String(length=20), nullable=False),
    sa.Column('entity_id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=500), nullable=False),
    sa.Column('url', sa.String(length=1000), nullable=False),
    sa.Column('summary', sa.Text(), nullable=True),
    sa.Column('published_at', sa.DateTime(), nullable=True),
    sa.Column('source', sa.String(length=50), nullable=False),
    sa.Column('crawled_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('url')
    )
    op.create_table('brand_collaborations',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('brand_a_id', sa.Integer(), nullable=False),
    sa.Column('brand_b_id', sa.Integer(), nullable=False),
    sa.Column('collab_name', sa.String(length=255), nullable=False),
    sa.Column('collab_category', sa.String(length=50), nullable=True),
    sa.Column('release_year', sa.Integer(), nullable=True),
    sa.Column('hype_score', sa.Integer(), nullable=False),
    sa.Column('source_url', sa.String(length=500), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['brand_a_id'], ['brands.id'], ),
    sa.ForeignKeyConstraint(['brand_b_id'], ['brands.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.add_column('brands', sa.Column('description_ko', sa.Text(), nullable=True))
    op.add_column('brands', sa.Column('tier', sa.String(length=20), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('brands', 'tier')
    op.drop_column('brands', 'description_ko')
    op.drop_table('brand_collaborations')
    op.drop_table('fashion_news')
    # ### end Alembic commands ###
