"""add_product_key_and_exchange_rates

Revision ID: c3ad818a067f
Revises: 66fc59a1f128
Create Date: 2026-02-26 21:04:45.294653

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c3ad818a067f'
down_revision: Union[str, Sequence[str], None] = '66fc59a1f128'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('exchange_rates',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('from_currency', sa.String(length=3), nullable=False),
    sa.Column('to_currency', sa.String(length=3), nullable=False),
    sa.Column('rate', sa.Float(), nullable=False),
    sa.Column('fetched_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('from_currency', 'to_currency', name='uq_currency_pair')
    )
    op.add_column('products', sa.Column('product_key', sa.String(length=300), nullable=True))
    op.create_index(op.f('ix_products_product_key'), 'products', ['product_key'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_products_product_key'), table_name='products')
    op.drop_column('products', 'product_key')
    op.drop_table('exchange_rates')
    # ### end Alembic commands ###
