"""partition price_history monthly on PostgreSQL

Revision ID: d4e5f6a7b8c9
Revises: c12883027b7b
Create Date: 2026-03-02 00:00:00.000000
"""
from __future__ import annotations

from typing import Sequence, Union

from alembic import op


# revision identifiers, used by Alembic.
revision: str = "d4e5f6a7b8c9"
down_revision: Union[str, Sequence[str], None] = "c12883027b7b"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def _create_monthly_partitions() -> None:
    for year in [2026, 2027]:
        for month in range(1, 13):
            start = f"{year}-{month:02d}-01"
            if month == 12:
                end = f"{year + 1}-01-01"
            else:
                end = f"{year}-{month + 1:02d}-01"
            part_name = f"price_history_{year}_{month:02d}"
            op.execute(
                f"""
                CREATE TABLE IF NOT EXISTS {part_name}
                PARTITION OF price_history
                FOR VALUES FROM ('{start}') TO ('{end}')
                """
            )


def upgrade() -> None:
    bind = op.get_bind()
    if bind.dialect.name != "postgresql":
        return

    op.execute("DROP INDEX IF EXISTS idx_price_history_product_crawled")
    op.execute("DROP INDEX IF EXISTS ix_price_history_product_id")
    op.execute("ALTER TABLE price_history RENAME TO price_history_unpartitioned")

    op.execute(
        """
        CREATE TABLE price_history (
            id INTEGER GENERATED BY DEFAULT AS IDENTITY,
            product_id INTEGER NOT NULL REFERENCES products(id),
            price NUMERIC(12, 2) NOT NULL,
            original_price NUMERIC(12, 2),
            currency VARCHAR(10),
            is_sale BOOLEAN NOT NULL DEFAULT FALSE,
            discount_rate INTEGER,
            crawled_at TIMESTAMP WITHOUT TIME ZONE NOT NULL DEFAULT NOW(),
            PRIMARY KEY (id, crawled_at)
        ) PARTITION BY RANGE (crawled_at)
        """
    )

    _create_monthly_partitions()
    op.execute("CREATE TABLE IF NOT EXISTS price_history_default PARTITION OF price_history DEFAULT")

    op.execute(
        """
        INSERT INTO price_history (
            id, product_id, price, original_price, currency, is_sale, discount_rate, crawled_at
        )
        SELECT
            id, product_id, price, original_price, currency, is_sale, discount_rate, crawled_at
        FROM price_history_unpartitioned
        """
    )
    op.execute(
        """
        SELECT setval(
            pg_get_serial_sequence('price_history', 'id'),
            COALESCE((SELECT MAX(id) FROM price_history), 1),
            true
        )
        """
    )

    op.execute(
        "CREATE INDEX idx_price_history_product_crawled ON price_history (product_id, crawled_at DESC)"
    )
    op.execute("DROP TABLE price_history_unpartitioned")


def downgrade() -> None:
    bind = op.get_bind()
    if bind.dialect.name != "postgresql":
        return

    op.execute("DROP INDEX IF EXISTS idx_price_history_product_crawled")
    op.execute("ALTER TABLE price_history RENAME TO price_history_partitioned_bak")
    op.execute(
        """
        CREATE TABLE price_history (
            id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
            product_id INTEGER NOT NULL REFERENCES products(id),
            price NUMERIC(12, 2) NOT NULL,
            original_price NUMERIC(12, 2),
            currency VARCHAR(10),
            is_sale BOOLEAN NOT NULL DEFAULT FALSE,
            discount_rate INTEGER,
            crawled_at TIMESTAMP WITHOUT TIME ZONE NOT NULL DEFAULT NOW()
        )
        """
    )
    op.execute(
        """
        INSERT INTO price_history (
            id, product_id, price, original_price, currency, is_sale, discount_rate, crawled_at
        )
        SELECT
            id, product_id, price, original_price, currency, is_sale, discount_rate, crawled_at
        FROM price_history_partitioned_bak
        """
    )
    op.execute(
        """
        SELECT setval(
            pg_get_serial_sequence('price_history', 'id'),
            COALESCE((SELECT MAX(id) FROM price_history), 1),
            true
        )
        """
    )
    op.execute(
        "CREATE INDEX IF NOT EXISTS idx_price_history_product_crawled ON price_history (product_id, crawled_at DESC)"
    )
    op.execute("DROP TABLE price_history_partitioned_bak CASCADE")
